Update. Test job to check for the coverage in ci pipeline

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -31,4 +31,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Run the test cases
-        run: go test -v ./...
+        run: go test -coverprofile=coverage.out ./...
+
+      - name: Test coverage check
+        env: 
+          TESTCOVERAGE_THRESHOLD: 99
+        run: |
+            echo "Checking test coverage"
+            echo "Desired threshold: $TESTCOVERAGE_THRESHOLD%"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print($1 > $2)}') )); then 
+              echo "OK"
+            else 
+              echo "The test coverage should be greater than $TESTCOVERAGE_THRESHOLD%"
+              echo "Failed"
+              exit 1
+            fi
